TG_CAT_HERBS = "Herbs";
TG_CAT_BFA_HERBS = "BFA Herbs";
TG_CAT_SHA_HERBS = "Shadowland Herbs";

TG_DB_HERBS = {

    { tag = "765",      name = "Silverleaf",            cat = TG_CAT_HERBS, skill = 1 },
    { tag = "2447",     name = "Peacebloom",            cat = TG_CAT_HERBS, skill = 1 },
    { tag = "2449",     name = "Earthroot",             cat = TG_CAT_HERBS, skill = 1 },
    { tag = "181166",   name = "Bloodthistle",          cat = TG_CAT_HERBS, skill = 1 },
    { tag = "785",      name = "Mageroyal",             cat = TG_CAT_HERBS, skill = 1 },
    { tag = "2450",     name = "Briarthorn",            cat = TG_CAT_HERBS, skill = 1 },
    { tag = "2452",     name = "Swiftthistle",          cat = TG_CAT_HERBS, skill = 1 },
    { tag = "3820",     name = "Stranglekelp",          cat = TG_CAT_HERBS, skill = 85 },
    { tag = "2453",     name = "Bruiseweed",            cat = TG_CAT_HERBS, skill = 1 },
    { tag = "3355",     name = "Wild Steelbloom",       cat = TG_CAT_HERBS, skill = 115 },
    { tag = "3369",     name = "Grave Moss",            cat = TG_CAT_HERBS, skill = 120 },
    { tag = "3356",     name = "Kingsblood",            cat = TG_CAT_HERBS, skill = 125 },
    { tag = "3357",     name = "Liferoot",              cat = TG_CAT_HERBS, skill = 150 },
    { tag = "3818",     name = "Fadeleaf",              cat = TG_CAT_HERBS, skill = 160 },
    { tag = "3821",     name = "Goldthorn",             cat = TG_CAT_HERBS, skill = 160 },
    { tag = "3358",     name = "Khadgar's Whisker",     cat = TG_CAT_HERBS, skill = 160 },
    -- Wintersbite
    { tag = "3819",     name = "Wintersbite",           cat = TG_CAT_HERBS, skill = 195 },
    { tag = "4625",     name = "Firebloom",             cat = TG_CAT_HERBS, skill = 205 },
    { tag = "8831",     name = "Purple Lotus",          cat = TG_CAT_HERBS, skill = 210 },
    { tag = "8836",     name = "Arthas' Tears",         cat = TG_CAT_HERBS, skill = 220 },
    { tag = "8838",     name = "Sungrass",              cat = TG_CAT_HERBS, skill = 230 },
    { tag = "8839",     name = "Blindweed",             cat = TG_CAT_HERBS, skill = 235 },
    { tag = "8845",     name = "Ghost Mushroom",        cat = TG_CAT_HERBS, skill = 245 },
    { tag = "8846",     name = "Gromsblood",            cat = TG_CAT_HERBS, skill = 250 },
    { tag = "13463",    name = "Dreamfoil",             cat = TG_CAT_HERBS, skill = 270 },
    { tag = "13464",    name = "Golden Sansam",         cat = TG_CAT_HERBS, skill = 260 },
    { tag = "13465",    name = "Mountain Silversage",   cat = TG_CAT_HERBS, skill = 280 },
    -- Plaguebloom
    { tag = "13466",    name = "Plaguebloom",           cat = TG_CAT_HERBS, skill = 285 },
    { tag = "13467",    name = "Icecap",                cat = TG_CAT_HERBS, skill = 290 },
    { tag = "13468",    name = "Black Lotus",           cat = TG_CAT_HERBS, skill = 300 },
    { tag = "22785",    name = "Felweed",               cat = TG_CAT_HERBS, skill = 300 },
    { tag = "22786",    name = "Dreaming Glory",        cat = TG_CAT_HERBS, skill = 301 },
    { tag = "22787",    name = "Ragveil",               cat = TG_CAT_HERBS, skill = 325 },
    { tag = "22789",    name = "Terocone",              cat = TG_CAT_HERBS, skill = 325 },
    { tag = "22790",    name = "Ancient Lichen",        cat = TG_CAT_HERBS, skill = 340 },
    { tag = "22791",    name = "Netherbloom",           cat = TG_CAT_HERBS, skill = 375 },
    { tag = "22792",    name = "Nightmare Vine",        cat = TG_CAT_HERBS, skill = 365 },
    { tag = "22793",    name = "Mana Thistle",          cat = TG_CAT_HERBS, skill = 375 },
    { tag = "22794",    name = "Fel Lotus",             cat = TG_CAT_HERBS, skill = 400 },
    { tag = "28714",    name = "Flame Cap",             cat = TG_CAT_HERBS, skill = 335 },
    { tag = "36901",    name = "Goldclover",            cat = TG_CAT_HERBS, skill = 375 },
    { tag = "36904",    name = "Tiger Lily",            cat = TG_CAT_HERBS, skill = 375 },
    { tag = "36906",    name = "Icethorn",              cat = TG_CAT_HERBS, skill = 375 },
    { tag = "36907",    name = "Talandra's Rose",       cat = TG_CAT_HERBS, skill = 400 },
    { tag = "36903",    name = "Adder's Tongue",        cat = TG_CAT_HERBS, skill = 400 },
    { tag = "36905",    name = "Lichbloom",             cat = TG_CAT_HERBS, skill = 400 },
    { tag = "37921",    name = "Deadnettle",            cat = TG_CAT_HERBS, skill = 400 },
    { tag = "39970",    name = "Fire Leaf",             cat = TG_CAT_HERBS, skill = 400 },
    { tag = "36908",    name = "Frost Lotus",           cat = TG_CAT_HERBS, skill = 400 },
    { tag = "52984",    name = "Stormvine",             cat = TG_CAT_HERBS, skill = 425 },
    { tag = "52986",    name = "Heartblossom",          cat = TG_CAT_HERBS, skill = 475 },
    { tag = "52983",    name = "Cinderbloom",           cat = TG_CAT_HERBS, skill = 425 },
    { tag = "52985",    name = "Azshara's Veil",        cat = TG_CAT_HERBS, skill = 500 },
    { tag = "52988",    name = "Whiptail",              cat = TG_CAT_HERBS, skill = 500 },
    { tag = "52987",    name = "Twilight Jasmine",      cat = TG_CAT_HERBS, skill = 500 },
    { tag = "13466",    name = "Sorrowmoss",            cat = TG_CAT_HERBS, skill = 285 },
    { tag = "3819",     name = "Dragon's Teeth",        cat = TG_CAT_HERBS, skill = 195 },
    { tag = "22797",    name = "Nightmare Seed",        cat = TG_CAT_HERBS, skill = 195 },
    { tag = "72237",    name = "Rain Poppy",            cat = TG_CAT_HERBS, skill = -1 },
    { tag = "72234",    name = "Green Tea Leaf",        cat = TG_CAT_HERBS, skill = -1 },
    { tag = "72235",    name = "Silkweed",              cat = TG_CAT_HERBS, skill = 500 },
    { tag = "79010",    name = "Snow Lily",             cat = TG_CAT_HERBS, skill = 500 },
    { tag = "79011",    name = "Fool's Cap",            cat = TG_CAT_HERBS, skill = 500 },
    { tag = "72238",    name = "Golden Lotus",          cat = TG_CAT_HERBS, skill = -1 },

}

TG_DB_BFA_HERBS = {
    --BFA--
    { tag = "152510",   name = "Anchor Weed",           cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "152505",   name = "Riverbud",              cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "152506",   name = "Star Moss",             cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "152507",   name = "Akunda's Bite",         cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "152508",   name = "Winter's Kiss",         cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "152509",   name = "Siren's Pollen",        cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "152511",   name = "Sea Stalk",             cat = TG_CAT_BFA_HERBS, skill = 1 },
    -- BFA 8.2 --
    { tag = "166888",   name = "Germinating Seed",      cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "169596",   name = "Zin'anthid Tentacle",   cat = TG_CAT_BFA_HERBS, skill = 1 },
    { tag = "168487",   name = "Zin'anthid",            cat = TG_CAT_BFA_HERBS, skill = 1 },
    -- Shadowland --
    { tag = "169701",   name = "Death Blossom",         cat = TG_CAT_BFA_HERBS, skill = 1 },
}

TG_DB_SHA_HERBS = {
    -- Shadowland --
    { tag = "169701",   name = "Death Blossom",         cat = TG_CAT_SHA_HERBS, skill = 1 },
    { tag = "168586",   name = "Rising Glory",          cat = TG_CAT_SHA_HERBS, skill = 1 },
}

TGH_PLUGIN_CATEGORIES = {
    { db = TG_DB_HERBS,     name = TG_CAT_HERBS,        smenu = TG_PREFIX_SHOW..TG_CAT_HERBS,       profession = "Herbalism"},
    { db = TG_DB_BFA_HERBS, name = TG_CAT_BFA_HERBS,    smenu = TG_PREFIX_SHOW..TG_CAT_BFA_HERBS,   profession = "BFA Herbalism"},
    { db = TG_DB_SHA_HERBS, name = TG_CAT_SHA_HERBS,    smenu = TG_PREFIX_SHOW..TG_CAT_SHA_HERBS,   profession = "Shadowlands Herbalism"}
}

TGH_MINABLES = {
    -- Flower sources
    { id = 1617, name = "Silverleaf" },
    { id = 1618, name = "Peacebloom" },
    { id = 1619, name = "Earthroot" },
    { id = 1620, name = "Mageroyal" },
    { id = 1621, name = "Briarthorn" },
    { id = 1622, name = "Bruiseweed" },
    { id = 1623, name = "Wild Steelbloom" },
    { id = 1624, name = "Kingsblood" },
    { id = 1628, name = "Grave Moss" },
    { id = 2450, name = "Briarthorn" },
    { id = 2041, name = "Liferoot" },
    { id = 2042, name = "Fadeleaf" },
    { id = 2043, name = "Khadgar's Whisker" },
    { id = 2044, name = "Dragon's Teeth" },
    { id = 2045, name = "Stranglekelp" },
    { id = 2046, name = "Goldthorn" },
    { id = 2866, name = "Firebloom" },
    { id = 142140, name = "Purple Lotus" },
    { id = 142141, name = "Arthas' Tears" },
    { id = 142142, name = "Sungrass" },
    { id = 142143, name = "Blindweed" },
    { id = 142144, name = "Ghost Mushroom" },
    { id = 142145, name = "Gromsblood" },
    { id = 176583, name = "Golden Sansam" },
    { id = 176584, name = "Dreamfoil" },
    { id = 176586, name = "Mountain Silversage" },
    { id = 176587, name = "Sorrowmoss" },
    { id = 176588, name = "Icecap" },
    { id = 176589, name = "Black Lotus" },
    { id = 181270, name = "Felweed" },
    { id = 181271, name = "Dreaming Glory" },
    { id = 181275, name = "Ragveil" },
    { id = 181276, name = "Flame Cap" },
    { id = 181277, name = "Terocone" },
    { id = 181278, name = "Ancient Lichen" },
    { id = 181279, name = "Netherbloom" },
    { id = 181280, name = "Nightmare Vine" },
    { id = 181281, name = "Mana Thistle" },
    { id = 185881, name = "Netherdust Bush" },
    { id = 189973, name = "Goldclover" },
    { id = 190169, name = "Tiger Lily" },
    { id = 190172, name = "Icethorn" },
    { id = 190170, name = "Talandra's Rose" },
    { id = 191019, name = "Adder's Tongue" },
    { id = 190171, name = "Lichbloom" },
    { id = 190172, name = "Icethorn" },
    { id = 190173, name = "Frozen Herb" },
    { id = 206085, name = "Frozen Herb" },
    { id = 190173, name = "Frozen Herb" },
    { id = 190174, name = "Frozen Herb" },
    { id = 190175, name = "Frozen Herb" },
    { id = 190176, name = "Frost Lotus" },
    { id = 202748, name = "Stormvine" },
    { id = 202749, name = "Azshara's Veil" },
    { id = 202750, name = "Heartblossom" },
    { id = 202751, name = "Twilight Jasmine" },
    { id = 202752, name = "Whiptail" },
    { id = 209349, name = "Green Tea Leaf" },
    { id = 209350, name = "Silkweed" },
    { id = 209351, name = "Snow Lily" },
    { id = 209353, name = "Rain Poppy" },
    { id = 209355, name = "Fool's Cap" },
    { id = 214510, name = "Sha-Touched Herb" },
    { id = 276242, name = "Anchor Weed" },
    { id = 276234, name = "Riverbud" },
    { id = 281870, name = "Riverbud" },
    { id = 281079, name = "Star Moss" },
    { id = 276236, name = "Star Moss" },
    { id = 281867, name = "Star Moss" },
    { id = 281868, name = "Star Moss" },
    { id = 276237, name = "Akunda's Bite" },
    { id = 276238, name = "Winter's Kiss" },
    { id = 276239, name = "Siren's Pollen" },
    { id = 281869, name = "Siren's Pollen" },
    { id = 276240, name = "Sea Stalk" },
    { id = 281872, name = "Sea Stalk" },
    -- BFA 8.2 --
    { id = 326598, name = "Zin'anthid" },
    -- SHA 9.2 --
    { id = 336686, name = "Death Blossom" },
    { id = 336690, name = "Rising Glory" },

}